#!/bin/bash

fail_no_git() {
    echo "Could not find git in your path.  Fix this and try again."
    exit 2
}

cd ~/.vim
GIT=`which git`
[[ -x "$GIT" ]] || fail_no_git
set -x
git submodule update --init
cd ~
[[ -h .vimrc ]] && rm -f .vimrc
[[ -f .vimrc ]] && mv .vimrc vimrc_save
ln -s .vim/vimrc .vimrc
